//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2rayN.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResUI_zh_Hans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUI_zh_Hans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("v2rayN.Resx.ResUI.zh-Hans", typeof(ResUI_zh_Hans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量导出订阅内容至剪贴板成功.
        /// </summary>
        internal static string BatchExportSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("BatchExportSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量导出分享URL至剪贴板成功.
        /// </summary>
        internal static string BatchExportURLSuccessfully {
            get {
                return ResourceManager.GetString("BatchExportURLSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先检查服务器设置.
        /// </summary>
        internal static string CheckServerSettings {
            get {
                return ResourceManager.GetString("CheckServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置格式不正确.
        /// </summary>
        internal static string ConfigurationFormatIncorrect {
            get {
                return ResourceManager.GetString("ConfigurationFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意,自定义配置完全依赖您自己的配置，不能使用所有设置功能。在自定义配置inbound中有socks port等于设置中的port时，系统代理才可用.
        /// </summary>
        internal static string CustomServerTips {
            get {
                return ResourceManager.GetString("CustomServerTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载开始....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载.
        /// </summary>
        internal static string downloadSpeed {
            get {
                return ResourceManager.GetString("downloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否下载? {0}.
        /// </summary>
        internal static string DownloadYesNo {
            get {
                return ResourceManager.GetString("DownloadYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换配置文件失败.
        /// </summary>
        internal static string FailedConversionConfiguration {
            get {
                return ResourceManager.GetString("FailedConversionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成默认配置文件失败.
        /// </summary>
        internal static string FailedGenDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGenDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取得默认配置失败.
        /// </summary>
        internal static string FailedGetDefaultConfiguration {
            get {
                return ResourceManager.GetString("FailedGetDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入自定义配置服务器失败.
        /// </summary>
        internal static string FailedImportedCustomServer {
            get {
                return ResourceManager.GetString("FailedImportedCustomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取配置文件失败.
        /// </summary>
        internal static string FailedReadConfiguration {
            get {
                return ResourceManager.GetString("FailedReadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写正确格式额外ID.
        /// </summary>
        internal static string FillCorrectAlterId {
            get {
                return ResourceManager.GetString("FillCorrectAlterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写正确格式服务器端口.
        /// </summary>
        internal static string FillCorrectServerPort {
            get {
                return ResourceManager.GetString("FillCorrectServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请正确填写KCP参数.
        /// </summary>
        internal static string FillKcpParameters {
            get {
                return ResourceManager.GetString("FillKcpParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写本地监听端口.
        /// </summary>
        internal static string FillLocalListeningPort {
            get {
                return ResourceManager.GetString("FillLocalListeningPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写密码.
        /// </summary>
        internal static string FillPassword {
            get {
                return ResourceManager.GetString("FillPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写服务器地址.
        /// </summary>
        internal static string FillServerAddress {
            get {
                return ResourceManager.GetString("FillServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写用户ID.
        /// </summary>
        internal static string FillUUID {
            get {
                return ResourceManager.GetString("FillUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不是正确的客户端配置文件，请检查.
        /// </summary>
        internal static string IncorrectClientConfiguration {
            get {
                return ResourceManager.GetString("IncorrectClientConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不是正确的配置，请检查.
        /// </summary>
        internal static string Incorrectconfiguration {
            get {
                return ResourceManager.GetString("Incorrectconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不是正确的服务端配置文件，请检查.
        /// </summary>
        internal static string IncorrectServerConfiguration {
            get {
                return ResourceManager.GetString("IncorrectServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化配置.
        /// </summary>
        internal static string InitialConfiguration {
            get {
                return ResourceManager.GetString("InitialConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 已是最新版本。.
        /// </summary>
        internal static string IsLatestCore {
            get {
                return ResourceManager.GetString("IsLatestCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 已是最新版本。.
        /// </summary>
        internal static string IsLatestN {
            get {
                return ResourceManager.GetString("IsLatestN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址.
        /// </summary>
        internal static string LvAddress {
            get {
                return ResourceManager.GetString("LvAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 别名.
        /// </summary>
        internal static string LvAlias {
            get {
                return ResourceManager.GetString("LvAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加密方式.
        /// </summary>
        internal static string LvEncryptionMethod {
            get {
                return ResourceManager.GetString("LvEncryptionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口.
        /// </summary>
        internal static string LvPort {
            get {
                return ResourceManager.GetString("LvPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型.
        /// </summary>
        internal static string LvServiceType {
            get {
                return ResourceManager.GetString("LvServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订阅.
        /// </summary>
        internal static string LvSubscription {
            get {
                return ResourceManager.GetString("LvSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试结果.
        /// </summary>
        internal static string LvTestResults {
            get {
                return ResourceManager.GetString("LvTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日下载.
        /// </summary>
        internal static string LvTodayDownloadDataAmount {
            get {
                return ResourceManager.GetString("LvTodayDownloadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日上传.
        /// </summary>
        internal static string LvTodayUploadDataAmount {
            get {
                return ResourceManager.GetString("LvTodayUploadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总下载.
        /// </summary>
        internal static string LvTotalDownloadDataAmount {
            get {
                return ResourceManager.GetString("LvTotalDownloadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总上传.
        /// </summary>
        internal static string LvTotalUploadDataAmount {
            get {
                return ResourceManager.GetString("LvTotalUploadDataAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传输协议.
        /// </summary>
        internal static string LvTransportProtocol {
            get {
                return ResourceManager.GetString("LvTransportProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中等.
        /// </summary>
        internal static string MediumFresh {
            get {
                return ResourceManager.GetString("MediumFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除原订阅内容.
        /// </summary>
        internal static string MsgClearSubscription {
            get {
                return ResourceManager.GetString("MsgClearSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载V2ray成功.
        /// </summary>
        internal static string MsgDownloadV2rayCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgDownloadV2rayCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入订阅内容失败.
        /// </summary>
        internal static string MsgFailedImportSubscription {
            get {
                return ResourceManager.GetString("MsgFailedImportSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取订阅内容成功.
        /// </summary>
        internal static string MsgGetSubscriptionSuccessfully {
            get {
                return ResourceManager.GetString("MsgGetSubscriptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未设置有效的订阅.
        /// </summary>
        internal static string MsgNoValidSubscription {
            get {
                return ResourceManager.GetString("MsgNoValidSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC更新失败.
        /// </summary>
        internal static string MsgPACUpdateFailed {
            get {
                return ResourceManager.GetString("MsgPACUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC更新成功.
        /// </summary>
        internal static string MsgPACUpdateSuccessfully {
            get {
                return ResourceManager.GetString("MsgPACUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析{0}成功.
        /// </summary>
        internal static string MsgParsingSuccessfully {
            get {
                return ResourceManager.GetString("MsgParsingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简化PAC成功.
        /// </summary>
        internal static string MsgSimplifyPAC {
            get {
                return ResourceManager.GetString("MsgSimplifyPAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始获取订阅内容.
        /// </summary>
        internal static string MsgStartGettingSubscriptions {
            get {
                return ResourceManager.GetString("MsgStartGettingSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始更新 {0}....
        /// </summary>
        internal static string MsgStartUpdating {
            get {
                return ResourceManager.GetString("MsgStartUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始更新 PAC....
        /// </summary>
        internal static string MsgStartUpdatingPAC {
            get {
                return ResourceManager.GetString("MsgStartUpdatingPAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订阅内容解码失败(非BASE64码).
        /// </summary>
        internal static string MsgSubscriptionDecodingFailed {
            get {
                return ResourceManager.GetString("MsgSubscriptionDecodingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在解压.......
        /// </summary>
        internal static string MsgUnpacking {
            get {
                return ResourceManager.GetString("MsgUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新订阅结束.
        /// </summary>
        internal static string MsgUpdateSubscriptionEnd {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新订阅开始.
        /// </summary>
        internal static string MsgUpdateSubscriptionStart {
            get {
                return ResourceManager.GetString("MsgUpdateSubscriptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新V2rayCore成功.
        /// </summary>
        internal static string MsgUpdateV2rayCoreSuccessfully {
            get {
                return ResourceManager.GetString("MsgUpdateV2rayCoreSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新V2rayCore成功！正在重启服务....
        /// </summary>
        internal static string MsgUpdateV2rayCoreSuccessfullyMore {
            get {
                return ResourceManager.GetString("MsgUpdateV2rayCoreSuccessfullyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此功能依赖Http全局代理,请先设置正确。.
        /// </summary>
        internal static string NeedHttpGlobalProxy {
            get {
                return ResourceManager.GetString("NeedHttpGlobalProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非vmess或ss协议.
        /// </summary>
        internal static string NonvmessOrssProtocol {
            get {
                return ResourceManager.GetString("NonvmessOrssProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非Vmess服务，此功能无效.
        /// </summary>
        internal static string NonVmessService {
            get {
                return ResourceManager.GetString("NonVmessService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到 v2ray-core，下载地址: {0}.
        /// </summary>
        internal static string NotFoundCore {
            get {
                return ResourceManager.GetString("NotFoundCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描完成,未发现有效二维码.
        /// </summary>
        internal static string NoValidQRcodeFound {
            get {
                return ResourceManager.GetString("NoValidQRcodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败，请检查重试.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写配置文件.
        /// </summary>
        internal static string PleaseFillConfigFileName {
            get {
                return ResourceManager.GetString("PleaseFillConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写备注.
        /// </summary>
        internal static string PleaseFillRemarks {
            get {
                return ResourceManager.GetString("PleaseFillRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写URL.
        /// </summary>
        internal static string PleaseFillUrl {
            get {
                return ResourceManager.GetString("PleaseFillUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择加密方式.
        /// </summary>
        internal static string PleaseSelectEncryption {
            get {
                return ResourceManager.GetString("PleaseSelectEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择协议.
        /// </summary>
        internal static string PleaseSelectProtocol {
            get {
                return ResourceManager.GetString("PleaseSelectProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选择服务器.
        /// </summary>
        internal static string PleaseSelectServer {
            get {
                return ResourceManager.GetString("PleaseSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快.
        /// </summary>
        internal static string QuickFresh {
            get {
                return ResourceManager.GetString("QuickFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器去重完成。原数量: {0}，现数量: {1}.
        /// </summary>
        internal static string RemoveDuplicateServerResult {
            get {
                return ResourceManager.GetString("RemoveDuplicateServerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否确定移除服务器?.
        /// </summary>
        internal static string RemoveServer {
            get {
                return ResourceManager.GetString("RemoveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户端配置文件保存在:{0}.
        /// </summary>
        internal static string SaveClientConfigurationIn {
            get {
                return ResourceManager.GetString("SaveClientConfigurationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务端配置文件保存在:{0}.
        /// </summary>
        internal static string SaveServerConfigurationIn {
            get {
                return ResourceManager.GetString("SaveServerConfigurationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 慢.
        /// </summary>
        internal static string SlowFresh {
            get {
                return ResourceManager.GetString("SlowFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意：此功能依赖Http全局代理!测试完成后,请手工调整Http全局代理和活动节点。.
        /// </summary>
        internal static string SpeedServerTips {
            get {
                return ResourceManager.GetString("SpeedServerTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC服务启动失败,请用管理员启动.
        /// </summary>
        internal static string StartPacFailed {
            get {
                return ResourceManager.GetString("StartPacFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动服务({0})....
        /// </summary>
        internal static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置成功
        ///{0}.
        /// </summary>
        internal static string SuccessfulConfiguration {
            get {
                return ResourceManager.GetString("SuccessfulConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功导入自定义配置服务器.
        /// </summary>
        internal static string SuccessfullyImportedCustomServer {
            get {
                return ResourceManager.GetString("SuccessfullyImportedCustomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功从剪贴板导入 {0} 个服务器.
        /// </summary>
        internal static string SuccessfullyImportedServerViaClipboard {
            get {
                return ResourceManager.GetString("SuccessfullyImportedServerViaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描导入URL成功.
        /// </summary>
        internal static string SuccessfullyImportedServerViaScan {
            get {
                return ResourceManager.GetString("SuccessfullyImportedServerViaScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前服务的真连接延迟: {0}.
        /// </summary>
        internal static string TestMeOutput {
            get {
                return ResourceManager.GetString("TestMeOutput", resourceCulture);
            }
        }
    }
}
